# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1c4c27507dd6ca0e13dab34059528d3bf83f94b7a3053ce0c00f5f2f64dbcbac048e0a0357443ce944a18c7c19e2c15c01af6186b1be41471c76a67fb2d4922

test:
  secret_key_base: dc2ec1656e2e8275e31007f41d14bb8707733d31b7c3ceeba537c8d6786e591d3f4d8ef551966c50b852e58fd1b24f572cd9c032233f82075798a557e25246ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
